language: rust
sudo: false
dist: trusty

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - libiberty-dev

rust:
  - nightly
  - beta
  - stable

env:
  global:
    - RUSTFLAGS="-C link-dead-code"

before_script:
  - cargo install cargo-kcov
  - cargo kcov --print-install-kcov-sh | $SHELL

script:
  - |
      cargo build &&
      cargo kcov --coveralls &&
      cargo bench &&
      cargo run --example test_authorization_header &&
      cargo run --example test_get &&
      cargo run --example test_post &&
      cargo doc

after_success: |
  [ "${TRAVIS_BRANCH}" = master ] &&
  [ "${TRAVIS_PULL_REQUEST}" == false ] &&
  [ "${TRAVIS_RUST_VERSION}" == stable ] &&
  cargo install ghp &&
  ghp target/doc &&
  git config user.name "Travis Documentation" &&
  git config user.email "name@example.com" &&
  git push -qf https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages 2>&1 > /dev/null

env:
  global:
    - secure: "OodvJ/Vj1BQtq/YrDd5DuuqwxujzZUlXlIkE2l9rVVsO0MeB/4vEu6POlGvjjKao0Z+wBbrhFkoYJE3PKvapUOMFRInc/y3HXcPS57zJBj0RIicB8SnXB7aLfW4T8smaYHtm799POPDUGQNGJRBjg2nz/BdFlgWDBZRUDZNj4YI="
