[package]
authors = ["gifnksm <makoto.nksm+github@gmail.com>"]
description = "OAuth client for Rust"
documentation = "https://gifnksm.github.io/oauth-client-rs"
license = "MIT OR Apache-2.0"
name = "oauth-client"
readme = "README.md"
repository = "https://github.com/gifnksm/oauth-client-rs"
version = "0.2.0"

[dependencies]
base64 = "0.5"
log = "0.3"
rand = "0.3"
reqwest = "0.5"
rust-crypto = "0.2"
time = "0.1"
url = "1.2.0"
